# Generated by Django 5.0.3 on 2026-05-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojauser',
            name='ojapass_narrative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
