# Generated by Django 5.0.3 on 2026-05-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ojauser_ojapass_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='escrow_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gig',
            name='escrow_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='escrow_transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
