# Generated by Django 5.0.3 on 2026-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gig_escrow_amount_gig_escrow_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajocontribution',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ojauser',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
