# Generated by Django 5.0.3 on 2026-05-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ajocontribution_transaction_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.paymentlink')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
