# Generated by Django 5.0.3 on 2026-05-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_loanoffer_loan_loanrepayment_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojauser',
            name='lga',
            field=models.CharField(blank=True, default='Surulere', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ojauser',
            name='role',
            field=models.CharField(choices=[('trader', 'Trader'), ('seeker', 'Seeker'), ('both', 'Both'), ('lender', 'Lender'), ('gov', 'Government')], default='trader', max_length=10),
        ),
    ]
