# Generated by Django 5.0.3 on 2026-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ojauser_lga_alter_ojauser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajocontribution',
            name='auto_debit_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ajomembership',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajomembership',
            name='missed_payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ojauser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
