# Generated by Django 5.0.3 on 2026-05-14 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ajocontribution_auto_debit_attempted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('tailoring', 'Tailoring'), ('catering', 'Catering'), ('delivery', 'Delivery'), ('cleaning', 'Cleaning'), ('it_tech', 'IT / Tech'), ('beauty', 'Beauty & Hair'), ('tutoring', 'Tutoring'), ('design', 'Design & Creative'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('work_date', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_contact', models.CharField(max_length=255)),
                ('amount_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('review_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('review_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_review', to='main.portfoliopost')),
            ],
        ),
    ]
