# Generated by Django 5.0.3 on 2026-05-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_portfoliopost_clientreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
